const products = [
    {
        'id': '1',
        'name': 'GG4 (Gorilla Glue #4)',
        'image': '/images/bong.PNG',
        'brand': 'hybrid',
        'category': 'flower',
        'description': 'A legendary hybrid strain (60% Indica / 40% Sativa) famous for its ultra-sticky resin and knockout effects',
        'rating': 5,
        'numReviews': 12,
        'price': 100,
        'countInStock': 100,
    },
    {
        'id': '2',
        'name': 'Blue Dream',
        'image': '/images/bubbler.PNG',
        'brand': 'hybrid',
        'category': 'flower',
        'description': '17-24% THC | Blueberry haze | Gentle cerebral lift + smooth body calm',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },
    {
        'id': '3',
        'name': 'Wedding Cake',
        'image': '/images/devices.PNG',
        'brand': 'hybrid',
        'category': 'flower',
        'description': '22-27% THC | Vanilla + peppery dough | Happy vibes with muscle-melting relief',
        'rating': 5,
        'numReviews': 12,
        'price': 100,
        'countInStock': 100,
    },
    {
        'id': '4',
        'name': 'Gelato',
        'image': '/images/pipes.PNG',
        'brand': 'hybrid',
        'category': 'flower',
        'description': 'Instagram’s favorite sweet trea, 20-25% THC | Sweet cream + lavender, Best for: relaxation',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },
    {
        'id': '5',
        'name': 'Northern Lights',
        'image': '/images/pipes.PNG',
        'brand': 'Indica',
        'category': 'flower',
        'description': 'One of the most famous indicas, known for its fast-acting relaxation and stress-melting properties',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },
    {
        'id': '6',
        'name': 'Purple Kush',
        'image': '/images/delta-8-thc-products-1.jpg',
        'brand': 'Indica',
        'category': 'flower',
        'description': 'A potent indica with a sweet, earthy aroma, delivering heavy sedation and pain relief',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },
    {
        'id': '7',
        'name': 'Granddaddy Purple',
        'image': '/images/disposables.jpg',
        'brand': 'Indica',
        'category': 'flower',
        'description': 'A classic indica with sweet grape and berry flavors, known for deep relaxation and stress relief',
        'rating': 5,
        'numReviews': 12,
        'price': 100,
        'countInStock': 100,
    },
    {
        'id': '8',
        'name': 'Sour Diesel',
        'image': '/images/juice.PNG',
        'brand': 'sativa',
        'category': 'flower',
        'description': 'A fast-acting sativa with a pungent diesel-like aroma, known for energizing and uplifting effects',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },
    {
        'id': '9',
        'name': 'Durban Poison',
        'image': '/images/placeholder.PNG',
        'brand': 'sativa',
        'category': 'flower',
        'description': 'A pure sativa from South Africa with a sweet, spicy taste, offering clear-headed, energetic effects',
        'rating': 5,
        'numReviews': 12,
        'price': 100,
        'countInStock': 100,
    },
    {
        'id': '10',
        'name': 'Green Crack',
        'image': '/images/smoke.PNG',
        'brand': 'sativa',
        'category': 'flower',
        'description': 'A potent sativa with tropical fruit flavors, providing intense focus and invigorating energy',
        'rating': 2,
        'numReviews': 1,
        'price': 100,
        'countInStock': 10,
    },

    {
        'id': '13',
        'name': 'Raw Garden',
        'image': '/images/rawc.PNG',
        'brand': 'indica',
        'category': 'Cartages',
        'description': 'Raw Garden vape cartridges generally offer a sweet, fruity flavor profile with indica-dominant effects.',
        'rating': 5,
        'numReviews': 12,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '14',
        'name': 'Big Chief',
        'image': '/images/bigc.PNG',
        'brand': 'sativa',
        'category': 'Cartages',
        'description': 'Big Chief delivers a refreshing and juicy experience, reminiscent of biting into a ripe watermelon.',
        'rating': 2,
        'numReviews': 1,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '15',
        'name': 'Friendly Farms',
        'image': '/images/frc.PNG',
        'brand': 'hybrid',
        'category': 'Cartages',
        'description': 'Friendly Farms effects makes you feel uplifted, happy, and relaxed.',
        'rating': 5,
        'numReviews': 12,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '16',
        'name': 'Friendly Farms',
        'image': '/images/frs.PNG',
        'brand': 'sativa',
        'category': 'Cartages',
        'description': 'Friendly Farms effects makes you feel uplifted, happy, and relaxed.',
        'rating': 2,
        'numReviews': 1,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '87',
        'name': 'GELONADE',
        'image': '/images/disp1.PNG',
        'brand': '1G & 3G',
        'category': 'Disposable Cart',
        'description': 'Piff 1g Disposable. Piff Exotics Edition variety pack 1 gram disposable, Liquid Diamonds.We have 5 differet flavors, for more info, Text/Call 202-209-9605.',
        'rating': 5,
        'numReviews': 12,
        'price': 40,
        'countInStock': 100,
    },
    {
        'id': '88',
        'name': 'HI-OCTANE',
        'image': '/images/disp1.PNG',
        'brand': '1G & 3G',
        'category': 'Disposable Cart',
        'description': 'Piff 1g Disposable. Piff Exotics Edition variety pack 1 gram disposable, Liquid Diamonds.We have 5 differet flavors, for more info, Text/Call 202-209-9605.',
        'rating': 2,
        'numReviews': 1,
        'price': 40,
        'countInStock': 10,
    },
    {
        'id': '187',
        'name': 'Pinaple Passion',
        'image': '/images/disp.PNG',
        'brand': '3G & 1G',
        'category': 'Disposable Cart',
        'description': 'Piff 3g Disposable. Piff Tropical XL Edition variety pack 3 gram disposable, 1.5G Live Resin + 1.5G Liquid Diamonds. We have 6 differet flavors, for more info, Text/Call 202-209-9605.',
        'rating': 5,
        'numReviews': 12,
        'price': 40,
        'countInStock': 100,
    },
    {
        'id': '188',
        'name': 'Grape Gelato',
        'image': '/images/disp.PNG',
        'brand': '3G & 1G',
        'category': 'Disposable Cart',
        'description': 'Piff 3g Disposable. Piff Tropical XL Edition variety pack 3 gram disposable, 1.5G Live Resin + 1.5G Liquid Diamonds. We have 6 differet flavors, for more info, Text/Call 202-209-9605.',
        'rating': 2,
        'numReviews': 1,
        'price': 40,
        'countInStock': 10,
    },
    {
        'id': '287',
        'name': 'Star Fruit',
        'image': '/images/disp.PNG',
        'brand': '3G & 1G',
        'category': 'Disposable Cart',
        'description': 'Piff 3g Disposable. Piff Tropical XL Edition variety pack 3 gram disposable, 1.5G Live Resin + 1.5G Liquid Diamonds.We have 6 differet flavors, for more info, Text/Call 202-209-9605.',
        'rating': 5,
        'numReviews': 12,
        'price': 40,
        'countInStock': 100,
    },
    {
        'id': '32',
        'name': 'Top-shelf preroll',
        'image': '/images/preroll.PNG',
        'brand': 'pre-rolls',
        'category': 'Prerolls',
        'description': 'Top Shelf 10 x 80, and 20 X 150',
        'rating': 2,
        'numReviews': 1,
        'price': 10,
        'countInStock': 10,
    },
    {
        'id': '33',
        'name': 'Premium preroll',
        'image': '/images/prr.PNG',
        'brand': 'Pre-rolls',
        'category': 'Prerolls',
        'description': 'Premium prerolls 10 x 80, and 20 X 150',
        'rating': 5,
        'numReviews': 12,
        'price': 10,
        'countInStock': 100,
    },
    {
        'id': '51',
        'name': 'Shatter',
        'image': '/images/shaa.PNG',
        'brand': '5g shatter',
        'category': 'Concentrates',
        'description': '5g shatter 50',
        'rating': 2,
        'numReviews': 1,
        'price': 50,
        'countInStock': 10,
    },
    {
        'id': '52',
        'name': 'Tincture',
        'image': '/images/thnc.PNG',
        'brand': '1000MG THC Tincture',
        'category': 'Concentrates',
        'description': 'THC tinctures emerge as an ideal choice for non-smokers or those seeking a discreet and rapidly effective cannabis solution',
        'rating': 2,
        'numReviews': 1,
        'price': 50,
        'countInStock': 100,
    },
    {
        'id': '76',
        'name': 'Trolli Gummi Candy',
        'image': '/images/gem.PNG',
        'brand': 'Edible 600 mg',
        'category': 'Edibles',
        'description': 'Gummy worms edibles 6X100',
        'rating': 5,
        'numReviews': 12,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '77',
        'name': 'Hyfly',
        'image': '/images/hig.PNG',
        'brand': 'Edible 600 mg',
        'category': 'Edibles',
        'description': 'Hyfly edibles 6X100',
        'rating': 2,
        'numReviews': 1,
        'price': 30,
        'countInStock': 10,
    },
    {
        'id': '78',
        'name': 'Stony Patch',
        'image': '/images/ste.PNG',
        'brand': 'Edible 500 mg',
        'category': 'Edibles',
        'description': 'Stony Patch edibles 6X100',
        'rating': 5,
        'numReviews': 12,
        'price': 30,
        'countInStock': 100,
    },
    {
        'id': '79',
        'name': 'Peach',
        'image': '/images/edibles2.PNG',
        'brand': 'Edible',
        'category': 'Edibles',
        'description': 'Peach ring edibles 5X100',
        'rating': 2,
        'numReviews': 1,
        'price': 30,
        'countInStock': 10,
    },
];

export { products };
